name: Backend Syntax & Lint

on:
  push:            # 🔥 fires on *every* push
  pull_request:    # 🔥 and on *every* PR

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: syntax & style check
        run: |
          # --exit-zero so we can selectively fail only on real errors.
          # E999 = syntax errors, F821/F822 = name/import errors, etc.
          flake8 backend/app \
            --select=E999,F821,F822 \
            --max-line-length=88
